### ISSUE TITLE
TASK [edgenet-kubernetes : Ensure Kubernetes APT GPG key is present] is failing on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by mpiraux** [EdgeNet-project/node#75]
When running the boostrap.sh script, the task installing the GPG key of the kubernetes repo is failing with:

```
TASK [edgenet-kubernetes : Ensure Kubernetes APT repository is present] ********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details., W:GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05, E:The repository 'http://apt.kubernetes.io kubernetes-xenial InRelease' is not signed."}
```

**Comment by mpiraux** [comment]
Adding the key using the deprecated apt-key and re-running the boostraph.sh script did the trick

```curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -```

**Comment by mpiraux** [comment]
FYI I fixed it in a fork but I am unsure how to bring this in an interoperable way in Ansible. 

https://github.com/EdgeNet-project/node/compare/main...mpiraux:edgenet-node:main

**Comment by ubombar** [comment]
Hello @mpiraux  and thank you for opening an issue. Let me look into how we can integrate it with Ansible.

**Comment by ubombar** [comment]
@mpiraux, I am trying to replicate the problem can you give some information about your setup?

**Comment by mpiraux** [comment]
I tried running the boostrap.sh script on a Ubuntu 22.04.2 x86_64 machine that was recently provisioned. The thing worth noting that comes to my mind is that I installed podman-docker which might conflict with EdgeNet.

**Comment by ubombar** [comment]
It looks like this is caused by preinstalled binaries but I am not an expert on the bootstrap script side. I think @cscognamiglio might give a better thought.

**Comment by ubombar** [comment]
Hello @mpiraux, I checked the implementation and it is working! Thank you for your contribution. I invite you to create a PR for these changes, so that we can merge with `main`.
